export * from './plazavea/frutas-y-verduras'
export * from './plazavea/carnes-aves-y-pescados'
export * from './plazavea/desayunos'
export * from './plazavea/lactos-y-huevos'
export * from './plazavea/quesos-y-fiambres'
export * from './plazavea/abarrotes'
export * from './plazavea/panederia-y-pasteleria'
export * from './plazavea/pollo-rostizado-y-comidas'
export * from './plazavea/congelados'
export * from './plazavea/bebidas'
export * from './plazavea/vinos-licores-y-cervezas'
export * from './plazavea/limpieza'
export * from './plazavea/cuidado-personal-y-salud'
export * from './plazavea/bebe-e-infantil'
export * from './plazavea/mascotas'
export * from './plazavea/ahorro-packs'
export * from './plazavea/mercadosaludable'
export * from './plazavea/automotriz'


